<?php

namespace ContainerWEU6ltR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BB111JWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BB111JW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BB111JW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\PanierController::ajouterAuPanier' => ['privates', '.service_locator.Gl3nBvd', 'get_ServiceLocator_Gl3nBvdService', true],
            'App\\Controller\\PanierController::commanderPanier' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PanierController::confirmationCommande' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PanierController::supprimerDuPanier' => ['privates', '.service_locator.Gl3nBvd', 'get_ServiceLocator_Gl3nBvdService', true],
            'App\\Controller\\ProduitController::delete' => ['privates', '.service_locator.Gl3nBvd', 'get_ServiceLocator_Gl3nBvdService', true],
            'App\\Controller\\ProduitController::edit' => ['privates', '.service_locator.Gl3nBvd', 'get_ServiceLocator_Gl3nBvdService', true],
            'App\\Controller\\ProduitController::index' => ['privates', '.service_locator.epy_BmF', 'get_ServiceLocator_EpyBmFService', true],
            'App\\Controller\\ProduitController::list' => ['privates', '.service_locator.epy_BmF', 'get_ServiceLocator_EpyBmFService', true],
            'App\\Controller\\ProduitController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ProduitController::show' => ['privates', '.service_locator.ViXcClx', 'get_ServiceLocator_ViXcClxService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.jpvOrpT', 'get_ServiceLocator_JpvOrpTService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.LDIxXnX', 'get_ServiceLocator_LDIxXnXService', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\PanierController:ajouterAuPanier' => ['privates', '.service_locator.Gl3nBvd', 'get_ServiceLocator_Gl3nBvdService', true],
            'App\\Controller\\PanierController:commanderPanier' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PanierController:confirmationCommande' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PanierController:supprimerDuPanier' => ['privates', '.service_locator.Gl3nBvd', 'get_ServiceLocator_Gl3nBvdService', true],
            'App\\Controller\\ProduitController:delete' => ['privates', '.service_locator.Gl3nBvd', 'get_ServiceLocator_Gl3nBvdService', true],
            'App\\Controller\\ProduitController:edit' => ['privates', '.service_locator.Gl3nBvd', 'get_ServiceLocator_Gl3nBvdService', true],
            'App\\Controller\\ProduitController:index' => ['privates', '.service_locator.epy_BmF', 'get_ServiceLocator_EpyBmFService', true],
            'App\\Controller\\ProduitController:list' => ['privates', '.service_locator.epy_BmF', 'get_ServiceLocator_EpyBmFService', true],
            'App\\Controller\\ProduitController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ProduitController:show' => ['privates', '.service_locator.ViXcClx', 'get_ServiceLocator_ViXcClxService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.jpvOrpT', 'get_ServiceLocator_JpvOrpTService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.LDIxXnX', 'get_ServiceLocator_LDIxXnXService', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\PanierController::ajouterAuPanier' => '?',
            'App\\Controller\\PanierController::commanderPanier' => '?',
            'App\\Controller\\PanierController::confirmationCommande' => '?',
            'App\\Controller\\PanierController::supprimerDuPanier' => '?',
            'App\\Controller\\ProduitController::delete' => '?',
            'App\\Controller\\ProduitController::edit' => '?',
            'App\\Controller\\ProduitController::index' => '?',
            'App\\Controller\\ProduitController::list' => '?',
            'App\\Controller\\ProduitController::new' => '?',
            'App\\Controller\\ProduitController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\PanierController:ajouterAuPanier' => '?',
            'App\\Controller\\PanierController:commanderPanier' => '?',
            'App\\Controller\\PanierController:confirmationCommande' => '?',
            'App\\Controller\\PanierController:supprimerDuPanier' => '?',
            'App\\Controller\\ProduitController:delete' => '?',
            'App\\Controller\\ProduitController:edit' => '?',
            'App\\Controller\\ProduitController:index' => '?',
            'App\\Controller\\ProduitController:list' => '?',
            'App\\Controller\\ProduitController:new' => '?',
            'App\\Controller\\ProduitController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
