<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWEU6ltR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWEU6ltR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWEU6ltR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWEU6ltR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWEU6ltR\App_KernelDevDebugContainer([
    'container.build_hash' => 'WEU6ltR',
    'container.build_id' => 'eb47bd26',
    'container.build_time' => 1713108507,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWEU6ltR');
